config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :test_controllers
  resources :locations
  resources :users
  resources :events
  
  root 'locations#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :test_controllers
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :location
  validates :title, :location_id, :event_date, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
     #validates_presence_of :address, :message => "can't be empty"
     #validates_length_of :address
     #validates :address, presence: true
     validates :name, :presence => { :message => "不能空白" }
     validates :address, :presence => { :message => "不能空白" }
     has_many :events
end

app/models/test_controller.rb
class TestController < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def admin?
         	 self.authadmin == 'EveryFirstAdmin'
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
    devise_parameter_sanitizer.for(:sign_up) << :authadmin
    devise_parameter_sanitizer.for(:account_update) << :authadmin
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
  
  def new
    @event = Event.new
  end
  
  def create
    #render text: event_params
    #return 
    @event = Event.new(event_params)
    
    respond_to do |format|
      if @event.save
        #format.html {render :index}
        redirect_to 'index'
      else
        format.html {render :new}
      end
    end
  end
  
  private
  def event_params
    params.require(:event).permit(:title, :location_id, :event_date)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  
  def index
    @alllocations = Location.all
    
    respond_to do |format|
      format.html
      format.xml {render :xml => @alllocations.to_xml}
      format.json {render :json => @alllocations.to_json}
    end
  end
  
  def new
    @location = Location.new
  end
  
  def create
    #render text: location_params
    #render text: params
    #return 
    
    @location = Location.new(location_params)
    #redirect_to 'index'
    #return
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location}
        #format.json {}
      else
        format.html { render :new }
        #format.json { render json: @location.errors, status: :unprocessable_entity }
        #format.json { render json: @location.errors}
      end
    end
  end
  
  def edit
    @location = Location.find(params[:id])
  end
  
  def update
    @updatelocation = Location.find(params[:id])
    @updatelocation.update(location_params)
    redirect_to action: "show"
  end
  
  def show
    #render text: params
    #return 
    @location = Location.find(params[:id])
    

  end
    
  def destroy
    #render text: params[:id]
    #return 
    @deletelocation = Location.find(params[:id])
    @deletelocation.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    def location_params
      params.require(:location).permit(:name,:gps,:address,:official_web)
    end
end

app/controllers/test_controllers_controller.rb
class TestControllersController < ApplicationController
  before_action :set_test_controller, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  
  # GET /test_controllers
  # GET /test_controllers.json
  def index
    @test_controllers = TestController.all
  end

  # GET /test_controllers/1
  # GET /test_controllers/1.json
  def show
  end

  # GET /test_controllers/new
  def new
    @test_controller = TestController.new
  end

  # GET /test_controllers/1/edit
  def edit
  end

  # POST /test_controllers
  # POST /test_controllers.json
  def create  
    @test_controller = TestController.new(test_controller_params)

    respond_to do |format|
      if @test_controller.save
        format.html { redirect_to @test_controller, notice: 'Test controller was successfully created.' }
        format.json { render :show, status: :created, location: @test_controller }
      else
        format.html { render :new }
        format.json { render json: @test_controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_controllers/1
  # PATCH/PUT /test_controllers/1.json
  def update
    respond_to do |format|
      if @test_controller.update(test_controller_params)
        format.html { redirect_to @test_controller, notice: 'Test controller was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_controller }
      else
        format.html { render :edit }
        format.json { render json: @test_controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_controllers/1
  # DELETE /test_controllers/1.json
  def destroy
    @test_controller.destroy
    respond_to do |format|
      format.html { redirect_to test_controllers_url, notice: 'Test controller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_controller
      @test_controller = TestController.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_controller_params
      params.require(:test_controller).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@allusers = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/test_controllers_helper.rb
module TestControllersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><i class="fa fa-star-o"></i> CoolPlayFun</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#"><i class="fa fa-music"></i> PERFORMER <span class="sr-only">(current)</span></a></li>
        <li><%= link_to '<i class="fa fa-user"></i> USER'.html_safe , users_path %></li>
		<li><%= link_to '<i class="fa fa-university"></i> LOCATION'.html_safe, locations_path%></li>
		<li><%= link_to '<i class="fa fa-calendar"></i> EVENTS'.html_safe, events_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
		
        <% if user_signed_in? %>
		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to '修改帳號', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
		<% else %>
			<li><%= link_to '註冊' , new_user_registration_path %></li>
			<li><%= link_to '登入' , new_user_session_path %></li>
		<% end %>
		
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/events/index.html.erb
<h1> This is Events Index page </h1>

<table class="table">
	<tr>
		<th>Name</th>
		<th>location</th>
		<th>date</th>
	</tr>

	<% @events.each do |e| %>
	<tr>
		<td><%= e.title %></td>
		<td><%= e.location.name || "" %></td>
		<td><%= e.event_date %></td>
	</tr>
	<% end %>

<!--	
	<tr>
		<td><%= "1" %></td>
		<td><%= "2" %></td>
		<td><%= "3" %></td>
	</tr>
-->	

<table/>

<%= link_to 'New Event', new_event_path, class:'btn btn-info' %>

app/views/events/new.html.erb
<h1>This is new page</h1>
<%= simple_form_for @event do |f| %>
<%= f.input :title %>
<%= f.association :location %>
<%= f.input :event_date %>
<%= f.submit %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>

<hr/>
<footer class="footer">
	<i class="fa fa-copyright"></i> Copyright by Bichon Inc.
</footer>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
	<%#= f.error_notification %>
	
	<%= f.input :name ,placeholder: 'location name'  , label: false , :required => true %>
	<%#= f.input :name , :required => true %>
	<%= f.input :address, placeholder: 'address'  , label: false , :required => true %>
	<%= f.input :official_web, placeholder: '官方網站', label: false %>
	<%= f.input :gps, placeholder: 'GPS' , label: false %>
	
	<%= f.button :submit %>
<% end %>

<hr/>

app/views/locations/edit.html.erb
<h1>This is edit Location page</h1>

<%= render 'form' %>

<%= link_to 'Show Location', location_path(@location), class:'btn btn-success' %>

app/views/locations/index.html.erb
<h1>This is location index page</h1>
<hr/>

<p id="notice"><%= notice %></p>

<table>
	<table class="table">	
		<% @alllocations.each do |location| %>
		<tr>
			<td class="col-sm-1"><%= location.id %></td>
			<td class="col-sm-3"><%= location.name %></td>
			<td class="col-sm-1"><%= link_to 'Show Location', location_path(location)%></td>
			<td class="col-sm-1"><%= link_to 'Edit Location', edit_location_path(location)%></td>
			<td class="col-sm-1"><%= link_to 'Destroy Location', location_path(location), :method => :delete %></td>
		</tr>
		<% end %>
	</table>
</table>

<hr/>

<%= link_to 'Add Location', new_location_path, class:'btn btn-info' %>

app/views/locations/new.html.erb
<h1>This is Add Location page</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<h1>This is show page</h1>

<table class="table">
	<tr>ID: <%= @location.id %></tr><br/>
	<tr>Name: <%= @location.name %></tr><br/>
	<tr>Address: <%= @location.address %></tr><br/>
	<tr>Official_web<%= @location.official_web %></tr><br/>
</table>

<%= link_to 'Back to Index', locations_path, class:'btn btn-info' %>
<%= link_to 'Edit Location', edit_location_path(@location), class:'btn btn-success' %>

app/views/test_controllers/_form.html.erb
<%= simple_form_for(@test_controller) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
	<%= f.input :name %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/test_controllers/edit.html.erb
<h1>Editing Test Controller</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_controller %> |
<%= link_to 'Back', test_controllers_path %>

app/views/test_controllers/index.html.erb
<p id="notice"><%= notice %></p>

<i class="fa fa-bolt fa-3x">Listing Test Controllers</i>
<br/>
<br/>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
	<table class="table">  
    <% @test_controllers.each do |test_controller| %>
      <tr>
		<td><%= test_controller.name %></td>
        <td><%= link_to 'Show', test_controller %></td>
<% if can? :update, test_controller %>
        <td><%= link_to 'Edit', edit_test_controller_path(test_controller) %></td>
<% end %>
<% if can? :destroy, test_controller %>
        <td><%= link_to 'Destroy', test_controller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>        

      </tr>
    <% end %>
	</table>
  </tbody>
  <%= link_to 'New Test controller', new_test_controller_path, class:"btn btn-success" %><br/>
  <hr/>

  <% if current_user %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
      <%= link_to('修改帳號', edit_registration_path(:user)) %>
  <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %>
  <% end %>
  
  <hr/>
</table>

app/views/test_controllers/new.html.erb
<h1>New Test Controller</h1>

<%= render 'form' %>

<%= link_to 'Back', test_controllers_path %>

app/views/test_controllers/show.html.erb
<p id="notice"><%= notice %></p>

<table class:'table'>
	<%= @test_controller.name %>
</table>

<hr/>

<%= link_to 'Edit', edit_test_controller_path(@test_controller) %> |
<%= link_to 'Back', test_controllers_path %>

app/views/users/index.html.erb
<h1>This is User Index page</h1>

<table class="table">
	<% @allusers.each do |user|%>
		<tr>
			<td><%= user.username %></td>
			<% if can? :delete , user%>
			<td><%= link_to 'Delete', user_path(user), method: :delete %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<hr/>

<%= link_to 'Create User', new_user_path, class:'btn btn-info' %>